@startuml
state UNUSED
state EMBRYO
state RUNNING
state RUNNABLE
state SLEEPING
state ZOMBIE

UNUSED --> EMBRYO: allocproc()
EMBRYO --> RUNNABLE: fork()/userinit()
RUNNABLE --> RUNNING: scheduler()
RUNNING --> RUNNABLE: interrupt
RUNNING --> SLEEPING: syscall
SLEEPING --> RUNNABLE: Event finish
RUNNING --> ZOMBIE: exit/killed
@enduml